name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List files (debug)
      run: ls -R .
      
    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++
      
    - name: Compile
      run: g++ Coba00.cpp -o main
      
    - name: Run
      run: ./main
      
    - name: make distcheck
      run: make distcheck
